DROP DATABASE IF EXISTS dbtransporte;
CREATE DATABASE dbTransporte;
USE sakila;

CREATE TABLE BOLETA (
    CODBOL char(7),
    FECBOL timestamp ,
    IDCLI int ,
    IDVEN int ,
    PREBOL int,
    NUMASI char(2) NOT NULL,
    CODDES char(3) NOT NULL,
    CONSTRAINT BOLETA_pk PRIMARY KEY (CODBOL)
);

CREATE TABLE BUS (
    CODBUS char(7),
    CANTASI char(2),
    CODMAR char(3),
    CONSTRAINT BUS_pk PRIMARY KEY (CODBUS)
);

CREATE TABLE CLIENTE (
    IDCLI int auto_increment,
    NOMCLI varchar(50),
    APECLI varchar(50),
    DNICLI char(8),
    CORCLI varchar(50),
    CELCLI char(9),
    CODUBI char(6),
    ESTCLI char(1),
    CONSTRAINT CLIENTE_pk PRIMARY KEY (IDCLI)
);

CREATE TABLE CONDUCTOR (
    IDCON int auto_increment,
    NOMCON varchar(50),
    APECON varchar(50),
    DNICON char(8),
    CELCON char(9),
    CODUBI char(6),
    CODPUES char(3),
    SUECON int,
    ESTVEN char(1),
    CONSTRAINT CONDUCTOR_pk PRIMARY KEY (IDCON)
) COMMENT 'Información del encargado del bus.';

CREATE TABLE DESTINO (
    CODDES char(3),
    NOMSAL varchar(50),
    NOMLLE varchar(50),
    CONSTRAINT DESTINO_pk PRIMARY KEY (CODDES)
);

CREATE TABLE DETALLE_BUS (
    CODDETBUS int NOT NULL,
    IDCON int NOT NULL,
    CODBUS char(7) NOT NULL,
    CONSTRAINT DETALLE_BUS_pk PRIMARY KEY (CODDETBUS)
);

CREATE TABLE MARCA (
    CODMAR char(3),
    NOMMAR varchar(45),
    MODMAR varchar(50),
    CONSTRAINT MARCA_pk PRIMARY KEY (CODMAR)
);

CREATE TABLE PUESTO (
    CODPUES char(3),
    NOMPUES varchar(60),
    AREPUES varchar(50),
    CONSTRAINT PUESTO_pk PRIMARY KEY (CODPUES)
);


CREATE TABLE UBIGEO (
    CODUBI char(6),
    NOMDEPA varchar(50),
    NOMPROV varchar(50),
    NOMDIST varchar(50),
    CONSTRAINT UBIGEO_pk PRIMARY KEY (CODUBI)
);

CREATE TABLE VENDEDOR (
    IDVEN int auto_increment,
    NOMVEN varchar(50),
    APEVEN varchar(50),
    DNIVEN char(8),
    CELVEN char(9),
    CODUBI char(6),
    CODPUES char(3),
    SUEVEN int,
    ESTVEN char(1),
    CONSTRAINT VENDEDOR_pk PRIMARY KEY (IDVEN)
);

-- Relaciones
ALTER TABLE BOLETA ADD CONSTRAINT BOLETA_DESTINO FOREIGN KEY BOLETA_DESTINO (CODDES)
    REFERENCES DESTINO (CODDES);

ALTER TABLE BOLETA ADD CONSTRAINT BOLETA_EMPLEADO FOREIGN KEY BOLETA_EMPLEADO (IDVEN)
    REFERENCES VENDEDOR (IDVEN);

ALTER TABLE BOLETA ADD CONSTRAINT CLIENTE_EMPLEADO_CODCLI FOREIGN KEY CLIENTE_EMPLEADO_CODCLI (IDCLI)
    REFERENCES CLIENTE (IDCLI);

ALTER TABLE CONDUCTOR ADD CONSTRAINT CONDUCTOR_PUESTO FOREIGN KEY CONDUCTOR_PUESTO (CODPUES)
    REFERENCES PUESTO (CODPUES);

ALTER TABLE CONDUCTOR ADD CONSTRAINT CONDUCTOR_UBIGEO FOREIGN KEY CONDUCTOR_UBIGEO (CODUBI)
    REFERENCES UBIGEO (CODUBI);

ALTER TABLE DETALLE_BUS ADD CONSTRAINT DETALLE_BOLETA_BUS FOREIGN KEY DETALLE_BOLETA_BUS (CODBUS)
    REFERENCES BUS (CODBUS);

ALTER TABLE DETALLE_BUS ADD CONSTRAINT DETALLE_BOLETA_CONDUCTOR FOREIGN KEY DETALLE_BOLETA_CONDUCTOR (IDCON)
    REFERENCES CONDUCTOR (IDCON);

ALTER TABLE VENDEDOR ADD CONSTRAINT EMPLEADO_PUESTO FOREIGN KEY EMPLEADO_PUESTO (CODPUES)
    REFERENCES PUESTO (CODPUES);

ALTER TABLE BUS ADD CONSTRAINT MARCA_BUS_CODMAR FOREIGN KEY MARCA_BUS_CODMAR (CODMAR)
    REFERENCES MARCA (CODMAR);

ALTER TABLE CLIENTE ADD CONSTRAINT UBIGEO_CLIENTE_CODUBI FOREIGN KEY UBIGEO_CLIENTE_CODUBI (CODUBI)
    REFERENCES UBIGEO (CODUBI);

ALTER TABLE VENDEDOR ADD CONSTRAINT UBIGEO_EMPLEADO_CODUBI FOREIGN KEY UBIGEO_EMPLEADO_CODUBI (CODUBI)
    REFERENCES UBIGEO (CODUBI);


